apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress