apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yml

helmGlobals:
  chartHome: ../../addons/cert-manager/charts

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  includeCRDs: true
  namespace: cert-manager
  valuesFile: values.yaml

