apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- network
# - cis
# - asm-config
# - asm-gateways
# - cert-manager
# - external-dns
- external-secrets
# - k8s-dashboard

# components:
#   - ../components/nginx
